apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodegoat
  template:
    metadata:
      labels:
        app: nodegoat
    spec:
      serviceAccountName: nodegoat-sa
      containers:
      - name: nodegoat
        image: DOCKER_IMAGE
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_URI
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
